[package]
name = "shared_library"
version = "0.1.2"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Easily bind to and load shared libraries"
license = "Apache-2.0/MIT"

[dependencies]
libc = "0.2"
lazy_static = "0.1"
